client:
  timeout:
    read: 60
    connect: 10
server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
logrus:
  level: debug
alfabank:
  ecom:
    url: https://web.rbsuat.com
databases:
  default:
    dsn: dbname=kvell user=kvell password=qazwsx host=127.0.0.1 pool_max_conns=10
